"""innovation analysis state

Revision ID: 06db756477da
Revises: 87c58741447b
Create Date: 2026-09-30 15:46:22.290729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06db756477da'
down_revision: Union[str, Sequence[str], None] = '87c58741447b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('innovations', sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('innovations', 'analysis')
    # ### end Alembic commands ###
