"""escalation assignment and notes

Revision ID: 4310f8724217
Revises: 8623fabb51aa
Create Date: 2026-09-30 18:40:56.906249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4310f8724217'
down_revision: Union[str, Sequence[str], None] = '8623fabb51aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escalations', sa.Column('assigned_to', sa.String(length=36), nullable=True))
    op.add_column('escalations', sa.Column('reviewer_notes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.create_foreign_key(None, 'escalations', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.drop_column('escalations', 'reviewer_notes')
    op.drop_column('escalations', 'assigned_to')
    # ### end Alembic commands ###
