"""initial domain schema

Revision ID: 87c58741447b
Revises: 
Create Date: 2026-09-30 15:34:43.097026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87c58741447b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=True),
    sa.Column('expected_abstention', sa.Boolean(), nullable=False),
    sa.Column('expected_document_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_provider', sa.String(length=40), nullable=False),
    sa.Column('embedding_provider', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.Column('authority_tier', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('access_level', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_jurisdiction'), 'sources', ['jurisdiction'], unique=False)
    op.create_table('terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=60), nullable=False),
    sa.Column('english', sa.String(length=200), nullable=True),
    sa.Column('sanskrit', sa.String(length=200), nullable=True),
    sa.Column('hindi', sa.String(length=200), nullable=True),
    sa.Column('botanical', sa.String(length=200), nullable=True),
    sa.Column('chemical', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ambiguity_note', sa.Text(), nullable=True),
    sa.Column('candidate_species', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_canonical'), 'terms', ['canonical'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('auth_provider', sa.String(length=40), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role', native_enum=False, length=40), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('confidential_mode', sa.Boolean(), nullable=False),
    sa.Column('retention_policy', sa.String(length=40), nullable=False),
    sa.Column('external_retrieval_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_hash', sa.String(length=80), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=False),
    sa.Column('domain', sa.String(length=60), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('publication_date', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=True),
    sa.Column('access_level', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=True),
    sa.Column('extraction_method', sa.String(length=40), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('supersedes_document_id', sa.String(length=36), nullable=True),
    sa.Column('superseded_by_document_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_jurisdiction'), 'documents', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('innovations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('innovation_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROFILED', 'IN_RESEARCH', 'IN_REVIEW', 'COMPLETED', name='innovation_status', native_enum=False, length=40), nullable=False),
    sa.Column('confidentiality_level', sa.Enum('PUBLIC_RESEARCH', 'INTERNAL', 'CONFIDENTIAL', name='confidentiality', native_enum=False, length=40), nullable=False),
    sa.Column('target_markets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wizard_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_innovations_workspace_id'), 'innovations', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'RESEARCHER', 'REVIEWER', 'VIEWER', name='workspace_role', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('innovation_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_innovation_id'), 'conversations', ['innovation_id'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('subsection', sa.String(length=300), nullable=True),
    sa.Column('chunk_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('injection_flag', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(section,'') || ' ' || coalesce(subsection,'')), 'A') || setweight(to_tsvector('english', content), 'B')", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_search_vector', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('innovation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('IP_REVIEW', 'REGULATORY_REVIEW', 'DOMAIN_REVIEW', 'HUMAN_REVIEW', name='escalation_type', native_enum=False, length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('open_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_professional', sa.String(length=200), nullable=False),
    sa.Column('packet', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'CLOSED', name='escalation_status', native_enum=False, length=40), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_innovation_id'), 'escalations', ['innovation_id'], unique=False)
    op.create_index(op.f('ix_escalations_workspace_id'), 'escalations', ['workspace_id'], unique=False)
    op.create_table('evidence_gaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('innovation_id', sa.String(length=36), nullable=False),
    sa.Column('gap_key', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('related', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_gaps_innovation_id'), 'evidence_gaps', ['innovation_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('innovation_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('innovation_id', sa.String(length=36), nullable=False),
    sa.Column('feature_type', sa.Enum('INGREDIENT', 'COMPOSITION', 'PROCESS', 'EXTRACTION', 'DELIVERY', 'DOSAGE_FORM', 'CLAIM', 'USE', 'MANUFACTURING', 'OTHER', name='feature_type', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normalized_term', sa.String(length=300), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_innovation_features_innovation_id'), 'innovation_features', ['innovation_id'], unique=False)
    op.create_table('innovation_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('innovation_id', sa.String(length=36), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('botanical_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chemical_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('process', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.String(length=200), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('intended_use', sa.Text(), nullable=True),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_market', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manufacturing_location', sa.String(length=200), nullable=True),
    sa.Column('structured_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terminology', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ambiguities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_method_used', sa.String(length=40), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('innovation_id')
    )
    op.create_table('patents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('publication_number', sa.String(length=60), nullable=False),
    sa.Column('application_number', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_date', sa.String(length=20), nullable=True),
    sa.Column('publication_date', sa.String(length=20), nullable=True),
    sa.Column('filing_date', sa.String(length=20), nullable=True),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('applicant', sa.String(length=300), nullable=True),
    sa.Column('inventor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patent_family_id', sa.String(length=60), nullable=True),
    sa.Column('classification_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_patents_patent_family_id'), 'patents', ['patent_family_id'], unique=False)
    op.create_index(op.f('ix_patents_publication_number'), 'patents', ['publication_number'], unique=False)
    op.create_table('regulatory_pathways',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('product_category', sa.String(length=200), nullable=False),
    sa.Column('category_key', sa.String(length=80), nullable=False),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.Column('framework', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claims_restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('labeling_considerations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_pathways_category_key'), 'regulatory_pathways', ['category_key'], unique=False)
    op.create_index(op.f('ix_regulatory_pathways_jurisdiction'), 'regulatory_pathways', ['jurisdiction'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('innovation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_innovation_id'), 'reports', ['innovation_id'], unique=False)
    op.create_index(op.f('ix_reports_workspace_id'), 'reports', ['workspace_id'], unique=False)
    op.create_table('scientific_studies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=300), nullable=True),
    sa.Column('study_type', sa.String(length=80), nullable=False),
    sa.Column('population', sa.Text(), nullable=True),
    sa.Column('intervention', sa.Text(), nullable=True),
    sa.Column('dosage', sa.String(length=200), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_level', sa.String(length=40), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('innovation_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('applicability', sa.String(length=60), nullable=False),
    sa.Column('authority_tier', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('why_retrieved', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('innovation_id', 'chunk_id', 'evidence_type')
    )
    op.create_index(op.f('ix_evidence_innovation_id'), 'evidence', ['innovation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('patent_feature_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('innovation_id', sa.String(length=36), nullable=False),
    sa.Column('innovation_feature_id', sa.String(length=36), nullable=False),
    sa.Column('patent_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('match_type', sa.String(length=40), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('matched_passage', sa.Text(), nullable=False),
    sa.Column('matched_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['innovation_feature_id'], ['innovation_features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('innovation_feature_id', 'patent_id')
    )
    op.create_index(op.f('ix_patent_feature_matches_innovation_id'), 'patent_feature_matches', ['innovation_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('innovation_id', sa.String(length=36), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('support_status', sa.Enum('SUPPORTED', 'PARTIALLY_SUPPORTED', 'UNSUPPORTED', 'CONFLICTING', 'INSUFFICIENT', name='support_status', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['innovation_id'], ['innovations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_conversation_id'), 'claims', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_claims_innovation_id'), 'claims', ['innovation_id'], unique=False)
    op.create_index(op.f('ix_claims_message_id'), 'claims', ['message_id'], unique=False)
    op.create_table('retrieval_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('retrieval_method', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rerank_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_results_conversation_id'), 'retrieval_results', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_retrieval_results_message_id'), 'retrieval_results', ['message_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('support_status', sa.Enum('SUPPORTED', 'PARTIALLY_SUPPORTED', 'UNSUPPORTED', 'CONFLICTING', 'INSUFFICIENT', name='support_status', native_enum=False, length=40), nullable=False),
    sa.Column('entailment_score', sa.Float(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_evidence_claim_id'), 'claim_evidence', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_evidence_claim_id'), table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_retrieval_results_message_id'), table_name='retrieval_results')
    op.drop_index(op.f('ix_retrieval_results_conversation_id'), table_name='retrieval_results')
    op.drop_table('retrieval_results')
    op.drop_index(op.f('ix_claims_message_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_innovation_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_conversation_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_patent_feature_matches_innovation_id'), table_name='patent_feature_matches')
    op.drop_table('patent_feature_matches')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_evidence_innovation_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('scientific_studies')
    op.drop_index(op.f('ix_reports_workspace_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_innovation_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_regulatory_pathways_jurisdiction'), table_name='regulatory_pathways')
    op.drop_index(op.f('ix_regulatory_pathways_category_key'), table_name='regulatory_pathways')
    op.drop_table('regulatory_pathways')
    op.drop_index(op.f('ix_patents_publication_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_patent_family_id'), table_name='patents')
    op.drop_table('patents')
    op.drop_table('innovation_profiles')
    op.drop_index(op.f('ix_innovation_features_innovation_id'), table_name='innovation_features')
    op.drop_table('innovation_features')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_evidence_gaps_innovation_id'), table_name='evidence_gaps')
    op.drop_table('evidence_gaps')
    op.drop_index(op.f('ix_escalations_workspace_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_innovation_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('ix_chunks_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_innovation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_innovations_workspace_id'), table_name='innovations')
    op.drop_table('innovations')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_jurisdiction'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_terms_canonical'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_sources_jurisdiction'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('organizations')
    op.drop_table('evaluation_runs')
    op.drop_table('evaluation_questions')
    # ### end Alembic commands ###
